name: ProtoFs

on:
  push:
    # For code coverage reports
    branches: [main]
    paths:
      - .github/workflows/protofs.yml
      - protofs/*
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/protofs.yml
      - protofs/*

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: protofs/go.mod
          cache-dependency-path: protofs/go.sum

      - run: |
          go -C protofs tool ginkgo run -r \
          --github-output \
          --race \
          --trace \
          --coverprofile=cover.profile

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          use_oidc: true
          files: cover.profile
          name: aferox/protofs

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: unmango/actions/setup-nix@3ec4ed5a6af9c00f6a39e079df488573c77ebda6 # v1.0.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#aferox-protofs
